dist: xenial
mono: none
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6

before_script:
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb && rm -f packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-5.0
  - dotnet --info

script:
  - cd src/BoardTest && dotnet run

branches:
    only:
        - master

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
