dist: xenial
mono: none
sudo: required

env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb && rm -f packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-5.0
  - dotnet --info

script:
  - cd src && ./testall

branches:
    only:
        - master
