#!/bin/bash
if [[ -z "$1" ]]; then
    CONFIG=Release
else
    CONFIG=$1
fi
NTHREADS=4
rm -f ../../tables/*.endgame
dotnet build --configuration ${CONFIG} || exit $?
bin/${CONFIG}/net5.0/EndgameTableGen pgen 2 ${NTHREADS} | tee tablegen.log || exit $?
if [[ -f ../../tables/reference/endgame.sha256 ]]; then
    cd ../../tables/
    sha256sum -c reference/endgame.sha256 || exit $?
fi
exit 0
