#!/bin/bash
SWEEPER=backward
CONFIG=Release
NTHREADS=2
NONKINGS=3
if [[ "$1" == "restart" ]]; then
    rm -rfv ../../tables/*.endgame
fi
rm -rfv ../../tables/*.temp ../../tables/work_* shutdown
dotnet build --configuration ${CONFIG} || exit $?
bin/${CONFIG}/net5.0/EndgameTableGen pgen ${NONKINGS} ${NTHREADS} ${SWEEPER} | tee pargen.log

# Capture error from EndgameTableGen even though tee sets $? ...
[[ ${PIPESTATUS[0]} == 0 ]] || exit 1
if [[ -f ../../tables/reference/endgame.sha256 ]]; then
    cd ../../tables/
    sha256sum -c reference/endgame.sha256 || exit $?
fi
exit 0
