#!/bin/bash
if [[ -z "$1" ]]; then
    CONFIG=Release
else
    CONFIG=$1
fi
SWEEPER=backward
rm -rf ../../tables/*.endgame ../../tables/work_* ../../tables/*.temp
dotnet build --configuration ${CONFIG} || exit $?
bin/${CONFIG}/net5.0/EndgameTableGen gen_${SWEEPER} 2 | tee regen.log
exit ${PIPESTATUS[0]}
