#!/bin/bash
if [[ -z "$1" ]]; then
    CONFIG=Debug
else
    CONFIG=$1
fi
rm -f ../../tables/*.endgame ../../tables/*.edge
dotnet build --configuration ${CONFIG} || exit $?
bin/${CONFIG}/net5.0/EndgameTableGen gen 2 | tee tablegen.log || exit $?
exit 0
