#!/bin/bash
if [[ -z "$1" ]]; then
    CONFIG=Debug
else
    CONFIG=$1
fi
SWEEPER=backward
rm -rf ../../tables/*.endgame ../../tables/work_*
dotnet build --configuration ${CONFIG} || exit $?
bin/${CONFIG}/net5.0/EndgameTableGen gen_${SWEEPER} 2 | tee tablegen.log || exit $?
exit 0
