#!/bin/bash

Fail()
{
    echo "FAIL($0): $1"
    exit 1
}

cd BoardTest || Fail "Could not change to BoardTest directory."
dotnet run || Fail "BoardTest"
cd ../PossibleMates || Fail "Could not change to PossibleMates directory."
dotnet run || Fail "PossibleMates"
cd .. || Fail "Could not change back to src directory."
cat pass.txt
exit 0
